# Site settings
title: Jennifer Tesolin's Blog
email: jtesolin@gmail.com
description: "A site that has many tutorials and tips for web developement."
baseurl: ""
url: "http://jenntesolin.com"

# Build settings
markdown: rdiscount

paginate: 10

permalink: /blog/:year/:month/:day/:title/
paginate_path: /blog/page/:num
