# Site settings
title: Jennifer Tesolin
description: "This is Jennifer Tesolin's personal web site. Located on this site are tutorials and tips for web developers."
baseurl: ""
url: "https://jenntesolin.com"
timezone : "America/Toronto"
plugins: [jekyll-paginate]

# Build Settings
include: [dist]
exclude: [Gemfile, Gemfile.lock, README.md, vendor, bin,changelog.md,wordpress.xml,package.json,Gruntfile.js,node_modules, .ruby-version, scripts, results]
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
textile_ext:   textile
permalink: /blog/:year/:month/:day/:title/
paginate: 10
paginate_path: "blog/page:num"
gems:
  - jekyll-feed
name: Jennifer Tesolin Website
feed:
  path: atom.xml

# Author Settings
author :
  name : Jennifer Tesolin
  email : me@jenntesolin.com
  location : Toronto (Canada)
  github : jennifert
  twitter : jenntes
