# Site settings
title: Jennifer Tesolin
description: "A site that has many tutorials and tips for web developement."
baseurl: ""
url: "http://jenntesolin.com"
timezone : "America/Toronto"

# Build settings
exclude: [Gemfile, Gemfile.lock, README.md, vendor, bin,changelog.md,wordpress.xml,package.json,Gruntfile.js,node_modules]
markdown: kramdown

permalink: /blog/:year/:month/:day/:title/

paginate: 10
paginate_path: "blog/page:num"

author :
  name : Jennifer Tesolin
  email : jtesolin@gmail.com
  location : Toronto (Canada)
  github : jennifert
  twitter : jenntes