# Site settings
title: Jennifer Tesolin's Blog
description: "A site that has many tutorials and tips for web developement."
baseurl: ""
url: "http://jenntesolin.com"
timezone : "America/Toronto"

# Build settings
markdown: rdiscount

paginate: 10

permalink: /blog/:year/:month/:day/:title/
paginate_path: /blog/page/:num

author :
  name : Jennifer Tesolin
  email : jtesolin@gmail.com
  location : Toronto (Canada)
  github : jennifert
  twitter : jenntes